// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

// Package marketplacecommerceanalyticsiface provides an interface for the AWS Marketplace Commerce Analytics.
package marketplacecommerceanalyticsiface

import (
	"github.com/upstartmobile/aws-sdk-go/aws/request"
	"github.com/upstartmobile/aws-sdk-go/service/marketplacecommerceanalytics"
)

// MarketplaceCommerceAnalyticsAPI is the interface type for marketplacecommerceanalytics.MarketplaceCommerceAnalytics.
type MarketplaceCommerceAnalyticsAPI interface {
	GenerateDataSetRequest(*marketplacecommerceanalytics.GenerateDataSetInput) (*request.Request, *marketplacecommerceanalytics.GenerateDataSetOutput)

	GenerateDataSet(*marketplacecommerceanalytics.GenerateDataSetInput) (*marketplacecommerceanalytics.GenerateDataSetOutput, error)
}
