// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package inspectoriface_test

import (
	"testing"

	"github.com/upstartmobile/aws-sdk-go/service/inspector"
	"github.com/upstartmobile/aws-sdk-go/service/inspector/inspectoriface"
	"github.com/stretchr/testify/assert"
)

func TestInterface(t *testing.T) {
	assert.Implements(t, (*inspectoriface.InspectorAPI)(nil), inspector.New(nil))
}
