// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package kinesisiface_test

import (
	"testing"

	"github.com/upstartmobile/aws-sdk-go/service/kinesis"
	"github.com/upstartmobile/aws-sdk-go/service/kinesis/kinesisiface"
	"github.com/stretchr/testify/assert"
)

func TestInterface(t *testing.T) {
	assert.Implements(t, (*kinesisiface.KinesisAPI)(nil), kinesis.New(nil))
}
