// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package cognitosynciface_test

import (
	"testing"

	"github.com/upstartmobile/aws-sdk-go/service/cognitosync"
	"github.com/upstartmobile/aws-sdk-go/service/cognitosync/cognitosynciface"
	"github.com/stretchr/testify/assert"
)

func TestInterface(t *testing.T) {
	assert.Implements(t, (*cognitosynciface.CognitoSyncAPI)(nil), cognitosync.New(nil))
}
