// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package iotiface_test

import (
	"testing"

	"github.com/upstartmobile/aws-sdk-go/service/iot"
	"github.com/upstartmobile/aws-sdk-go/service/iot/iotiface"
	"github.com/stretchr/testify/assert"
)

func TestInterface(t *testing.T) {
	assert.Implements(t, (*iotiface.IoTAPI)(nil), iot.New(nil))
}
